### ISSUE TITLE
Possible Road map for toric varieties

### ISSUE THREAD

**Issue by HereAround** [oscar-system/JToric.jl#82]
The following is a list of tasks that I believe would be interesting to look into for toric varieties.

Of course, I do not claim that this list is complete, neither that the points need to be addressed in this order. Some of the points might also be debatable/need to be sharpened. Still, I hope that this gives a first impression of a possible roadmap.

I would be happy to hear what people think about this.

- [ ] Coordinate ring of torus
- [ ] List of variables of coordinate ring of torus
- [ ] The rational function of a character
- [ ] Cartier divisors, in particular collectively the group of Cartier torus invariant divisors
- [ ] Support polymake's CARTIER_DATA
- [ ] Cache computed properties:
-  More sophisticated show methods for toric varieties and toric divisors,
- Allow the user to choose the variable names of the Cox ring and the coordinate ring of the torus to their liking. (For example, I would like to label homogeneous coordinates introduced by a blowup by `e`.)
- Remember genesis of a toric variety, e.g. if it was obtained as direct product and if so, apply refined algorithms.
- Remember all toric divisors created for a toric variety and cache their properties as well.
- [ ] Comparison among toric varieties (e.g. isprojective_space, isdirect_product_of_projective_space, isdelPezzo etc.).
- [ ] Construct toric varieties from triangulations (likely via topcom).
- [ ] Construct toric varieties from GLSM charges.
- [ ] Support Cox variety.
- [ ] Toric morphisms.
- [ ] Line bundles:
- Picard group,
- cohomologies via cohomCalg or chamber counting,
- use cohomCalg to identify vanishing sets (key for many algorithms in the ToricVarieties_project).
- [ ]  Support famous vector bundles:
- Tangent and cotangent bundle of toric varieties.
-  Normal and tangent bundle of complete intersections.
- Compute resolutions and use cohomCalg to try to compute their cohomologies. (Will of course not always work, but is a quick first check.)
- [ ] Extend to coherent sheaves and their cohomologies (many algorithms in the ToricVarieties_project).
- [ ] Intersection theory in the Chow ring.
